name: credit-card-fraud-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.12.8=haa95532_0
  - certifi=2020.12.5=py39haa95532_0
  - cycler=0.10.0=py_2
  - freetype=2.10.4=h546665d_0
  - git=2.23.0=h6bb4b03_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=67.1=h33f27b4_0
  - intel-openmp=2020.2=254
  - jpeg=9d=h8ffe710_0
  - kiwisolver=1.3.1=py39h2e07f2f_0
  - libclang=10.0.1=default_hf44288c_1
  - libpng=1.6.37=h1d00b33_2
  - matplotlib=2.2.5=h57928b3_3
  - matplotlib-base=2.2.5=py39h4546143_2
  - mkl=2020.2=256
  - mkl-service=2.3.0=py39h196d8e1_0
  - mkl_fft=1.0.6=py39h054117c_0
  - mkl_random=1.0.2=py39h848d8c7_0
  - numpy=1.19.2=py39h729668d_0
  - numpy-base=1.19.2=py39hbd0edd7_0
  - openssl=1.1.1i=h2bbff1b_0
  - pandas=1.1.5=py39hf11a4ad_0
  - pip=20.3.3=py39haa95532_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39hcbf5309_6
  - pyqt-impl=5.12.3=py39h415ef7b_6
  - pyqt5-sip=4.19.18=py39h415ef7b_6
  - pyqtchart=5.12=py39h415ef7b_6
  - pyqtwebengine=5.12.1=py39h415ef7b_6
  - python=3.9.1=h6244533_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2020.4=pyhd3eb1b0_0
  - qt=5.12.9=hb2cf2c5_0
  - scipy=1.5.2=py39h14eb087_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - setuptools=51.0.0=py39haa95532_2
  - six=1.15.0=py39haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - tornado=6.1=py39hb82d6ee_0
  - tzdata=2020d=h14c3975_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - altair==4.1.0
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - base58==2.0.1
    - bleach==3.2.1
    - blinker==1.4
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - colorama==0.4.4
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - gitdb==4.0.5
    - gitpython==3.1.11
    - idna==2.10
    - ipykernel==5.4.2
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - kaggle==1.5.10
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - packaging==20.8
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pickleshare==0.7.5
    - pillow==8.0.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - pycparser==2.20
    - pydeck==0.5.0
    - pygments==2.7.3
    - pyrsistent==0.17.3
    - python-slugify==4.0.1
    - pywin32==300
    - pywinpty==0.5.7
    - pyzmq==20.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - requests==2.25.1
    - scikit-learn==0.24.0
    - send2trash==1.5.0
    - smmap==3.0.4
    - streamlit==0.73.1
    - terminado==0.9.1
    - testpath==0.4.4
    - text-unidecode==1.3
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - toolz==0.11.1
    - tqdm==4.54.1
    - traitlets==5.0.5
    - tzlocal==2.1
    - urllib3==1.26.2
    - validators==0.18.2
    - watchdog==1.0.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
